### PR TITLE
php56.extensions.redis: 3.1.4 → 3.1.6

### PR DESCRIPTION
**Pull request by jtojnar**
cc @mkg20001

### CODE REVIEW

**Comment by mkg20001** [comment]
Are there breaking changes in 4.x.x? We should be able to go all the way up to 4.3.0 https://github.com/phpredis/phpredis/issues/1691#issuecomment-567957346

**Comment by jtojnar** [comment]
Yes, see https://github.com/phpredis/phpredis/blob/develop/Changelog.md#400---2018-03-07-github-pecl

**Comment by jtojnar** [comment]
But I am not sure if we care about them.

**Comment by mkg20001** [comment]
We could make a redis4 module, or upgrade redis to 4.x and add a redis3 module

**Comment by mkg20001** [comment]
Personally I'd go for redis 4 upgrade and making redis3 a module for those that have a problem with the breaking changes

**Pull request merged**
