### PR TITLE
feat: add composer 1

### LINKED ISSUE #196: Composer 1
Hey,

I would like to need Composer 1 for old projects. Is it fine to add it to this repository as it contains already also old PHP versions 😅

### PR DESCRIPTION
**Pull request by shyim**
Fixes #196 

```
shyim in nix-phps on  add-composer-1 [?] took 4m15s 
❯ ./result/bin/composer -V
Composer version 1.10.26 2022-04-13 16:39:56
```

### CODE REVIEW

**Review by drupol — APPROVED** [review]
Looks pretty ok for me. Thanks for your contribution :)

**Comment by jtojnar** [comment]
Looks good, unless we also want to cache it, in which case it should be added to the CI.

**Comment by drupol** [comment]
Not necessary...it's using the official phar.

**Comment by jtojnar** [comment]
It could be a matter of not having to download stdenv (assuming rest of the environment is cached). But if someone still needs Composer 1, they probably have bigger problems.

**Comment by drupol** [comment]
Haha that's actually a very nice way of seeing the thing...

**Pull request merged**
