### PR TITLE
PHP-7.4.27 has been added

### PR DESCRIPTION
**Pull request by ktak-007**

### CODE REVIEW

**Comment by drupol** [comment]
What were you trying to do ? You need PHP 7.4.27 ?

**Comment by ktak-007** [comment]
Sorry, I've added PR to fossar/nix-phps by mistake. Now I've added it to my fork ktak-007/nix-phps. It is enough for my purposes at this moment.

**Comment by drupol** [comment]
PHP 7.4.27 has been included in `NixOS/nixpkgs` at this commit: https://github.com/NixOS/nixpkgs/commit/4f26cbfadb587554667d85f41689e36a741626f7

So you can do:

`nix flake update --override-input nixpkgs github:NixOS/nixpkgs/4f26cbfadb587554667d85f41689e36a741626f7`

Then you'll be able to use PHP 7.4.27 without creating your own custom repo.

**Comment by ktak-007** [comment]
Thank you for your help! But there is another problem - I  need ext-ssh2 in my php-7.4.27. I don't understand how to make new php extension with overlays. I created my own ktak-007/nixpkgs and I've added ssh2 module here. May be it will be correct add php-7.4.27 to my own ktak-007/nixpkgs and don't use nix-phps - I'm not sure yet.

**Comment by jtojnar** [comment]
Nixpkgs no longer supports PHP 7 so you would either need to base your Nixpkgs fork on the old version, or use nix-phps. I would recommend sending a PR introducing ssh2 extension to Nixpkgs (you can use https://github.com/NixOS/nixpkgs/pull/106867 as a starting point) and then updating nix-phps to the Nixpkgs version containing the extensions.

In a pinch, you could also add the extension to `pkgs/package-overrides.nix` in your fork of nix-phps.

**Pull request closed without merging**
