### PR TITLE
php82: php82-beta1 -> php82-beta2

### PR DESCRIPTION
**Pull request by drupol**

### CODE REVIEW

**Comment by drupol** [comment]
That test was not failing in `8.2-beta1`

```
=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
pcntl_setpriority() - Check for errors [tests/pcntl_setpriority_error_linux.phpt]
=====================================================================
```

Find the complete build log here: https://gist.github.com/drupol/a3fd7c7febee964ad595540b32530332

Do you think I should an issue in `php/php-src` ?

**Comment by jtojnar** [comment]
First, we need to get the actual test protocol. Build it with `nix build .#php82.extensions.pcntl --keep-failed` and then look at `php-8.2.0beta2/ext/pcntl/php_test_results*` in the reported build directory.

**Comment by jtojnar** [comment]
Another thing you can check is the `tests/pcntl_setpriority_error_linux.phpt` file in the PHP source code for any recent changes.

**Comment by drupol** [comment]
> Another thing you can check is the `tests/pcntl_setpriority_error_linux.phpt` file in the PHP source code for any recent changes. And the changelog of course.

That file has been introduced in this commit (https://github.com/php/php-src/commit/520bb2ec6ca01698f863cb16a5e9a28764df01ae#diff-d517133d2e2c271fcdba556de2330cd984828e7cb14fd42e93a43106aab2b3c2). This test is failing is failing on CI.

**Review by jtojnar — APPROVED** [review]

**Pull request merged**
