### PR TITLE
Re-use existing workflow "loophp/flake-lock-update-workflow".

### PR DESCRIPTION
**Pull request by drupol**
This PR:

- [x] Simplify the Github workflow action and use a standardized one to update `flake.nix`

### CODE REVIEW

**Comment by jtojnar** [comment]
Last time I tried https://github.com/DeterminateSystems/update-flake-lock, there were some issues. Though I no longer recall details.

Also, does `loophp/flake-lock-update-workflow` have any extra features? I was not able to glean that from the readme. If not, I would rather skip the indirection.

**Comment by drupol** [comment]
There's currently no other feature foreseen for version `1.0.0`.

We could imagine later on to create a diff between the previous and current commit and display the changes in the PR... but that is a feature which is not implemented and I really wish I could have it.

The main idea behind this is to unify and re-use the same workflow to update `flake.lock` files.

I'm already using it here:

* https://github.com/loophp/nix-shell/blob/master/.github/workflows/upgrade-flakes.yaml
* https://github.com/drupol/nixos-x260/blob/master/.github/workflows/upgrade-flakes.yaml

I will use it more and more... and the good thing is that those files are very small and identical.

**Comment by drupol** [comment]
Going to merge this and see if it fixes the issue in #64

**Comment by jtojnar** [comment]
One problem with this is that it no longer includes a link to the PR in the log:

https://github.com/fossar/nix-phps/runs/4816408898?check_suite_focus=true

**Comment by jtojnar** [comment]
Also, if we are to use a third partly action, I would rather use https://github.com/DeterminateSystems/update-flake-lock directly since having the dependency hidden makes it much harder to change the action.

**Comment by drupol** [comment]
Ok, going to make the update!

**Pull request merged**
