### PR TITLE
php82: add sysvsem

### PR DESCRIPTION
**Pull request by shyim**
Similar to https://github.com/NixOS/nixpkgs/pull/193921

### CODE REVIEW

**Comment by drupol** [comment]
Should this be enabled by default ?

**Comment by shyim** [comment]
image

It is not there without. Any of my Symfony with Lock component projects explode without it :)

**Comment by drupol** [comment]
Right.

To be honest, this is the first time I see this extension.

IMHO, I don't think it needs to be enabled by default, unless there is something I miss.

If I were you, I would use a custom version of PHP including sysvsem instead. It's easy to do.

If you share your flake.nix file, I can assist you.

Cheers.

**Review by jtojnar — COMMENTED** [review]
Consider also adding it to other older versions where available. I think we should follow Nixpkgs as closely as possible, and aim to reduce the differences between PHP versions, both in this repo  and between to prevent confusion.

**Comment by drupol** [comment]
> Should this be enabled by default ?

@jtojnar ^^

**Comment by jtojnar** [comment]
If it is enabled by default in Nixpkgs, then we should do the same.

**Comment by drupol** [comment]
It's enabled indeed. This PR is therefore legit. Validating it.

**Comment by drupol** [comment]
@shyim Do you plan to upgrade your PR ?

**Comment by shyim** [comment]
@drupol I have added it to all versions :)

**Comment by drupol** [comment]
All good, thanks !

**Pull request merged**
