### PR TITLE
fix: xdebug versions

### PR DESCRIPTION
**Pull request by guillemcanal**
This fix select the proper Xdebug version according to a given PHP version.

My code is pretty naïve since I discovered Nix a couple of days ago :) Feel free to suggest improvements :)

### CODE REVIEW

**Comment by jtojnar** [comment]
Thanks. The code looks reasonable.

- How did you determine the compatibility?
  - Would be nice to add a comment to the source code.
  - I found http://xdebug.org/docs/compat but according to that PHP 7.0 supports at most xdebug 2.7.
- Also we should test this on CI:
  Example: https://github.com/fossar/nix-phps/blob/abadbdff8fc8c41dd2ebb64a8c66be98ea950796/.github/workflows/build.yaml#L51-L52

**Comment by guillemcanal** [comment]
Hi @jtojnar, I determined the compatibility using https://mlocati.github.io/pecl-info/#xdebug.  
I'm updating the CI file to test Xdebug builds :)

As of PHP 7.0, Xdebug v2.9.0 work like a charm: 

```shell
gcanal in ~/Projects/nix-shell on  master [!] via 🐘 v7.0.33 via ❄️  impure (php-7.0.33) 
$ php -v
PHP 7.0.33 (cli) (built: Dec  4 2018 17:23:06) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.9.0, Copyright (c) 2002-2019, by Derick Rethans
```

**Comment by guillemcanal** [comment]
@jtojnar Just checked the link you provided, this is strange indeed, we may need to double check with @derickr

**Comment by guillemcanal** [comment]
@jtojnar https://github.com/xdebug/xdebug/blob/2.9.0/package.xml According to xdebug source code, v2.9.0 should be compatible with PHP 7.0.x https://github.com/xdebug/xdebug/blob/2.9.0/package.xml

**Comment by derickr** [comment]
Xdebug 2 is no longer supported.

And neither is PHP < 7.4 (from next week).

In any case, the version matrix is correct and don't use 2.9 with PHP 7.9.

**Comment by guillemcanal** [comment]
@derickr thanks for your insight :) 

I made a fix accordingly

**Comment by jtojnar** [comment]
Thanks.

**Pull request merged**
